# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Jul 28 15:22:20 2025
# ------------------------------------------------

package:
  name: micromamba
  version: 2.3.1
source:
  - url: https://github.com/mamba-org/mamba/archive/refs/tags/2.3.1.tar.gz
    sha256: a742b22c656f736408e0f044d412674ce9cfa84e8b85e9475afa5477f28a94ef
    folder: mamba
build:
  number: '0'
  string: '0'
  ignore_run_exports_from:
    - fmt
    - libarchive-minimal-static
    - libcurl
    - libsolv
    - openssl
    - spdlog
    - zlib
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.5 hf13058a_0
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - cctools_osx-64 1021.4 haa85c18_1
    - clang 19.1.7 default_h576c50e_3
    - clang-19 19.1.7 default_h3571c67_3
    - clang_impl_osx-64 19.1.7 hc73cdc9_25
    - clang_osx-64 19.1.7 h7e5c614_25
    - clangxx 19.1.7 default_heb2e8d1_3
    - clangxx_impl_osx-64 19.1.7 hb295874_25
    - clangxx_osx-64 19.1.7 h7e5c614_25
    - cmake 3.31.6 h477996e_0
    - compiler-rt 19.1.7 h52031e2_0
    - compiler-rt_osx-64 19.1.7 hc6f8467_0
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 954.16 hf1c22e8_1
    - libclang-cpp19.1 19.1.7 default_h3571c67_3
    - libcurl 8.14.1 h5dec5d8_0
    - libcxx 20.1.8 h3d58e20_1
    - libcxx-devel 19.1.7 h7c275be_1
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.1 h21dd04a_0
    - libiconv 1.18 h4b5e92a_1
    - libllvm19 19.1.7 hc29ff6c_1
    - liblzma 5.8.1 hd471939_2
    - libnghttp2 1.64.0 hc7306c3_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h4cb831e_0
    - libxml2 2.13.8 h93c44a6_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 h3fe3016_1
    - llvm-tools-19 19.1.7 he90a8e3_1
    - macosx_deployment_target_osx-64 10.13 hbc8f3bb_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.13.1 h0ba0a54_0
    - openssl 3.5.1 hc426f3f_0
    - rhash 1.4.5 ha44c9a9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.5 hf13058a_0
    - c-ares-static 1.34.5 hf13058a_0
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - cli11 2.5.0 h92383a6_0
    - cpp-expected 1.1.0 hd6aca1a_1
    - fmt 11.2.0 hbf61d64_0
    - krb5 1.21.3 h37d8d59_0
    - krb5-static 1.21.3 h37d8d59_0
    - libarchive-minimal-static 3.8.1 lgpl_h45cdce8_0
    - libcurl 8.14.1 h5dec5d8_0
    - libcurl-static 8.14.1 h5dec5d8_0
    - libcxx 20.1.8 h3d58e20_1
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libev-static 4.33 h10d778d_2
    - libiconv 1.18 h4b5e92a_1
    - liblzma 5.8.1 hd471939_2
    - liblzma-devel 5.8.1 hd471939_2
    - liblzma-static 5.8.1 h357f2ed_2
    - libnghttp2 1.64.0 hc7306c3_0
    - libnghttp2-static 1.64.0 hbd15cdf_0
    - libopenssl-static 3.5.1 hd471939_0
    - libsolv 0.7.34 h6fd32b5_0
    - libsolv-static 0.7.34 hebd868d_0
    - libssh2 1.11.1 hed3591d_0
    - libssh2-static 1.11.1 hed3591d_0
    - libzlib 1.3.1 hd23fc13_2
    - lz4-c 1.10.0 h240833e_1
    - lz4-c-static 1.10.0 h694c41f_1
    - ncurses 6.5 h0622a9a_3
    - nlohmann_json 3.12.0 h92383a6_0
    - openssl 3.5.1 hc426f3f_0
    - reproc-cpp-static 14.2.5.post0 h240833e_0
    - reproc-static 14.2.5.post0 h6e16a3a_0
    - simdjson 3.13.0 h9275861_0
    - simdjson-static 3.13.0 h20888b2_0
    - spdlog 1.15.3 hcdbecca_1
    - xz-static 5.8.1 h357f2ed_2
    - yaml-cpp-static 0.8.0 h92383a6_0
    - zlib 1.3.1 hd23fc13_2
    - zstd 1.5.7 h8210216_2
    - zstd-static 1.5.7 hba1c700_2
  run:
    - __osx >=10.13
    - libcxx >=19
test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"
    - test ! -f "${PREFIX}/etc/profile.d/mamba.sh"
    - micromamba --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"
    - micromamba create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'
about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZLIB_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba
extra:
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - jjerphan
    - mariusvniekerk
    - pavelzw
    - wolfv
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250728.3.1
  remote_url: https://github.com/conda-forge/micromamba-feedstock
  sha: 77dc48c1bc1e05fbcba3ae85f5d466c5f52cf93a
